calculation_of_fire_parameters/calc/urls.py
from django.urls import path

calculation_of_fire_parameters/calculation_of_fire_parameters/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('fire/', include('fire.urls')),
    path('admin/', admin.site.urls),
]

calculation_of_fire_parameters/fire/urls.py
from django.urls import path

from . import views

app_name = 'fire'

urlpatterns = [
    path('', views.fire_form, name='fire_form'),
    path('list/', views.fire_list, name='fire_list'),
]

calculation_of_fire_parameters/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

calculation_of_fire_parameters/calc/models.py
from django.db import models

# Create your models here.

calculation_of_fire_parameters/fire/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import gettext_lazy as _
#from django.db.models.signals import pre_save
#from django.dispatch import receiver


class Fire(models.Model):

    OBJECTS = {
        (1, 'Административное здание'),
        (2, 'Больница или школа'),
        (3, 'Библиотека или торговое предприятие'),
        (4, 'Склад льноволокна'),
        (5, 'Склад текстильных изделий'),
        (6, 'Склад резинотехнических изделий'),
        (7, 'Склад леса в штабелях'),
        (8, 'Склад пиломатериалов'),
        (9, 'Типография'),
        (10, 'Ремонтный зал ангара'),
    }

    name = models.CharField(
        verbose_name='Название пожара',
        max_length=50
    )
    time = models.IntegerField(
        verbose_name='Время с момента начала пожара',
        validators=[MinValueValidator(1), MaxValueValidator(60)],
        help_text='Введите время от 1 минуты до 60 минут',
    )
    corner = models.IntegerField(
        verbose_name='Угол распространения пожара',
        validators=[MinValueValidator(0), MaxValueValidator(180)],
        help_text='Введите значение от 0 градусов до 180 градусов',
    )
    object_type = models.PositiveSmallIntegerField(
        verbose_name='Объект пожара',
        choices=OBJECTS,
        blank=False,
        default=1
    )
    description = models.TextField(
        verbose_name='Описание',
        blank=True,
        help_text='Необязательное поле'
    )

    class Meta:
        verbose_name = _("пожар")
        verbose_name_plural = _("пожары")

    def __str__(self):
        return self.name


class Calculate(models.Model):
    squere_first_ten = models.FloatField('Площадь пожара за первые 10 минут')
    squere = models.FloatField('Площадь пожара')
    perimeter = models.FloatField('Периметр пожара')
    front = models.FloatField('Фронт пожара')
    speed_of_squere = models.FloatField('Скорость роста площади пожара')
    line_speed = models.FloatField('Линейная скорость роста пожара')
    front_speed = models.FloatField('Скорость роста фронта пожара')
    object_type = models.CharField('Тип объекта', max_length=50)
    name = models.CharField('Название пожара', max_length=50)
    time = models.IntegerField('Время с момента начала пожара')
    corner = models.IntegerField('Угол распространения пожара')
    description = models.TextField('Описание', blank=True)

    class Meta:
        verbose_name = _("Параметры пожара")
        verbose_name_plural = _("Параметры пожара")


#@receiver(pre_save, sender=Calculate)
#def update_fire_in_Calculate(sender, instance, **kwargs):
#    instance.fire = instance.Fire.id

calculation_of_fire_parameters/homepage/models.py
from django.db import models

# Create your models here.

calculation_of_fire_parameters/fire/forms.py
from django import forms

from .models import Fire


class FireForm(forms.ModelForm):
    class Meta:
        model = Fire
        fields = '__all__'
        widgets = {
            'description': forms.Textarea({'cols': '22', 'rows': '5'}),
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

calculation_of_fire_parameters/calc/views.py
from django.shortcuts import render

# Create your views here.

calculation_of_fire_parameters/fire/views.py
from django.shortcuts import render, get_object_or_404
from .models import Fire, Calculate
from .forms import FireForm


PI = 3.14

CHOICE_RESULT = {
    1: 'Административное здание',
    2: 'Больница или школа',
    3: 'Библиотека или торговое предприятие',
    4: 'Склад льноволокна',
    5: 'Склад текстильных изделий',
    6: 'Склад резинотехнических изделий',
    7: 'Склад леса в штабелях',
    8: 'Склад пиломатериалов',
    9: 'Типография',
    10: 'Ремонтный зал ангара',
}

CHOICE_VALUES = {
    1: 1.2,
    2: 2.5,
    3: 0.9,
    4: 4,
    5: 0.4,
    6: 1.5,
    7: 0.7,
    8: 2.3,
    9: 0.7,
    10: 1.3,
    }


def fire_form(request, pk=None, ):
    if pk is not None:
        instance = get_object_or_404(Fire, pk=pk)
    else:
        instance = None
    form = FireForm(request.POST or None, instance=instance)
    context = {'form': form}
    if form.is_valid():
        first_mod = form.save()

        choice1_value = CHOICE_VALUES[first_mod.object_type]
        var1 = first_mod.time
        var2 = first_mod.corner
        object_type = CHOICE_RESULT[first_mod.object_type]
        name = first_mod.name
        time = first_mod.time
        corner = first_mod.corner
        description = first_mod.description

        if var2 < 1:
            squere_first_ten = round(PI * ((0.5 * choice1_value * 10)**2))
            squere = round(PI * ((choice1_value * (var1-10))**2))
            perimeter = round(2 * PI * choice1_value * var1)
            front = perimeter
            speed_of_squere = round(PI * (choice1_value)**2 * var1)
            line_speed = round(choice1_value)
            front_speed = round(2 * PI * choice1_value)
        else:
            squere_first_ten = round(0.5 * PI * ((0.5 * choice1_value * 10)**2))
            squere = round(0.5 * PI * ((choice1_value * (var1-10))**2))
            perimeter = round(choice1_value * var1 * (2 + var2))
            front = round(var2 * choice1_value * var1)
            speed_of_squere = round(0.5 * var2 * (choice1_value)**2 * var1)
            line_speed = round(choice1_value)
            front_speed = round(2 * var2 * choice1_value)

        Calculate.objects.create(
            squere_first_ten=squere_first_ten,
            squere=squere,
            perimeter=perimeter,
            front=front,
            speed_of_squere=speed_of_squere,
            line_speed=line_speed,
            front_speed=front_speed,
            object_type=object_type,
            name=name,
            time=time,
            corner=corner,
            description=description,
        )

    return render(request, 'fire/fire_form.html', context)


def fire_list(request):
    fires = Fire.objects.all()
    calculations = Calculate.objects.all()
    context = {
        'fires': fires,
        'calculations': calculations,
        }
    return render(request, 'fire/fire_list.html', context)

calculation_of_fire_parameters/homepage/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'homepage/index.html')

calculation_of_fire_parameters/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title>РПнПО</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container pt-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

calculation_of_fire_parameters/templates/fire/fire_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Калькулятор пожара
{% endblock %}

{% block content %}

<div class="card col-4">
  <div class="card-header">
    Калькулятор
  </div>
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="Отправить" %}
      <a class="btn btn-outline-secondary btn px-3" href="{% url 'fire:fire_list' %}">Список всех расчетов</a>
    </form>
  </div>
</div>
{% with data=form.instance %}
{% if form.is_valid %}
  <h2>Пожар "{{ data.name }}" сохранен!</h2>
  <p>Номер расчета: {{ data.id }}</p>
  <hr>
{% endif %}
{% endwith %}
{% endblock %}

calculation_of_fire_parameters/templates/fire/fire_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  {% for calc in calculations %}
    <div> <!-- Обернём каждую запись в тег div -->
      <div> <!-- Текст обернём в отдельный вложенный div -->
        <p><b>Название пожара: {{ calc.name }}</b></p></li>
        <ul>
          <li><p>Время с момента начала пожара: {{ calc.time }}</p></li>
          <li><p>Угол пожара: {{ calc.corner }}</p></li>
          <li><p>Формула расчёта пожара: {% if calc.corner > 0  %}Угловая{% else %}Круговая {% endif %}
          <li><p>Объект пожара: {{ calc.object_type }}</p></li>
          <li><p>Описание пожара: {{ calc.description }}</p></li>
          <li><p>Площадь пожара за первые 10 минут: {{ calc.squere_first_ten }}</p></li>
          <li><p> Площадь пожара за все время: {{ calc.squere }} м2</p></li>
          <li><p> Периметр пожара за все время: {{ calc.perimeter }} м</p></li>
          <li><p> Фронт пожара за все время: {{ calc.front }} м</p></li>
          <li><p> Скорость роста площади пожара: {{ calc.speed_of_squere }} м2 в минуту</p></li>
          <li><p> Линейная скорость роста периметра пожара: {{ calc.line_speed }} м в минуту</p></li>
          <li><p> Скорость роста фронта пожара: {{ calc.front_speed }} м в минуту</p></li>
        </ul>
      </div>
      {% if not forloop.last %}
        <hr>
      {% endif %}
    </div>
  {% endfor %}
{% endblock content %}

calculation_of_fire_parameters/templates/homepage/index.html
{% extends "base.html" %}
{% load static %} 

{% block title %} Главная страница {% endblock title %}

{% block content %}
<div class="p-5 pb-mb-4 text-center">
  <h3 class="display-8 fw-bold">Программная система для расчёта параметров развития пожара на производственном объекте в Тульской области</h3>
</div>

<div class="pricing-header p-4 pb-md-4 mx-auto text-center">
  <div class="text-center">
    <img src="{% static 'img/MCHS.png' %}" width="200" height="250" class="rounded" alt="" />
  </div>
</div>

<div class="pricing-header p-5 pb-md-4 text-center">
  <div>
    <h3 class="display-8 fw-bold">С помощью данного онлайн ресурса сотрудники главного управления МЧС России по Тульской области могут выполнять расчёты параметров развития пожара на производственном объекте</h3>
    <div class="p-3 pb-mb-4 text-center"></div>
    <div class="col-lg-9 mx-auto">
      <p class="lead mb-4"><b> Перед началом выполнения расчёта параметров распространения пожара, необходимо подготовить данные о текущем пожаре, такие как: время с момента начала пожара и тип объекта, на котором начался пожар. </b></p>
      <p class="lead mb-4"><b> Для расчёта параметров перейдите на страницу расчётов, выберите формулу для расчёта параметров развития пожара и введите время с момента начала пожара, введите угол распространения пожара (только для угловой формулы) и выберите тип объекта, на котором начался пожар. </b></p>
      <p class="lead mb-4"><b> Результаты расчёта будут предоставлены после нажатия кнопки "Рассчитать" на отдельной странице, подготовленой для печати. </b></p>
      <div class="p-3 pb-mb-4 text-center"></div>
      <div class="pricing-header p-4 pb-md-4 mx-auto text-center">
        <div class="text-center">
          <img src="{% static 'img/1234.jpg' %}" width="700" height="300" class="rounded" alt="" />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

calculation_of_fire_parameters/templates/includes/footer.html
{% load static %}
<hr>
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="{% url "homepage:homepage" %}" class="nav-link px-2 text-muted">Главная</a></li>
      <li class="nav-item"><a href="{% url "fire:fire_form" %}" class="nav-link px-2 text-muted">Калькулятор</a></li>
      <li class="nav-item"><a href="{% url "fire:fire_list" %}" class="nav-link px-2 text-muted">Список пожаров</a></li>
    </ul>
    <p class="text-center text-muted">
      Дипломная работа Черного Кирилла Игоревича, 
      выпускника 4-го курса АГЗ МЧС России имени 
      генерал-лейтенанта Д.И. Михайлика</p>
    <p class="text-center text-muted">&copy; 2023 ВКР</p>
  </footer>
</div>  
</footer>

calculation_of_fire_parameters/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar shadow">
    <div class="container">
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'homepage:homepage' %} active {% endif %}"
              href="{% url 'homepage:homepage' %}">
              Главная
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'fire:fire_form' %} active {% endif %}"
              href="{% url 'fire:fire_form' %}">
              Калькулятор пожара
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'fire:fire_list' %} active {% endif %}"
              href="{% url 'fire:fire_list' %}">
              Список пожаров
            </a>
          </li>
        </ul>
      {% endwith %}
      <a class="navbar-brand" href="{% url 'homepage:homepage' %}">
      <img src="{% static 'img/logotip.png' %}" height="50" class="d-inline-block align-top" alt="">            
      </a>
    </div>      
  </nav>
</header>